file_format: "1"
id: yellowjacket
name: Yellowjacket
type: shield
url: https://github.com/sporaktu/yellowjacket-config
requires: [nice_nano_v2]
features:
  - keys
siblings:
  - yellowjacket_left
  - yellowjacket_right
layouts:
  compatible: yellowjacket
  layout:
    - [ 0,  1,  2,  3,        4,  5,  6,  7]
    - [ 8,  9, 10, 11, 12,   13, 14, 15, 16, 17]
    - [18, 19, 20, 21, 22,   23, 24, 25, 26, 27]
    - [          28, 29,   30, 31]
